---
# If you want to explicitly define an interface that ALL control nodes
# should use to propagate the VIP, define it here. Otherwise, kube-vip
# will determine the right interface automatically at runtime.
kube_vip_iface: null

# Name of the master group
group_name_master: master

server_init_args: >-
  {%- set master_ip = hostvars[groups[group_name_master | default('master')][0]].k3s_node_ip | split(",") | first | ansible.utils.ipwrap -%}
  {%- set cluster_init = '--cluster-init' if ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname'] else '' -%}
  {%- set server_arg = '--server https://' + master_ip + ':6443' if ansible_hostname != hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname'] else '' -%}
  {%- set token_arg = '--token ' + k3s_token if groups[group_name_master | default('master')] | length > 1 else '' -%}
  {{ [cluster_init, server_arg, token_arg, extra_server_args | default('')] | select('string') | join(' ') }}
