---
apiVersion: v1
kind: Deployment
metadata:
  name: wireguard
  namespace: wg
  labels:
    app: wireguard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      initContainers:
        - name: sysctls
          image: busybox
          command:
          - sh
          - -c
          - sysctl -w net.ipv4.ip_forward=1 && sysctl -w net.ipv4.conf.all.forwarding=1 && sysctl -w net.ipv4.conf.all.src_valid_mark=1
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
      containers:
        - name: wireguard
          image: ghcr.io/wg-easy/wg-easy
          ports:
          - containerPort: 51820
            protocol: UDP
          - containerPort: 51821
            protocol: TCP
          env:
            - name: WG_HOST
              value: "your public address" # Replace by your public IP address (curl -s https://checkip.amazonaws.com)
            - name: WG_DEFAULT_DNS
              value: "192.168.1.84" # Replace by your own or any DNS server
            - name: WG_DEFAULT_ADDRESS
              value: "10.33.0.x"
            - name: WG_POST_UP
              value: "iptables -t nat -A POSTROUTING -s 10.33.0.0/24 -o eth0 -j MASQUERADE"
            - name: "WG_POST_DOWN"
              value: "iptables -t nat -D POSTROUTING -s 10.33.0.0/24 -o eth0 -j MASQUERADE"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
            privileged: true
          resources:
            requests:
              memory: 64Mi
              cpu: "300m"
            limits:
              memory: 512Mi
          volumeMounts:
            - name: wireguard-volume
              mountPath: /etc/wireguard
      volumes:
        - name: wireguard-volume
          persistentVolumeClaim:
            claimName: wireguard-pvc
