---
apiVersion: v1
kind: Service
metadata:
  name: wireguard-sv
  namespace: wg
  labels:
    app: wireguard
spec:
  selector:
    app: wireguard
  ports:
  - name: wireguard
    protocol: UDP
    port: 51820
    targetPort: 51820
  - name: ui
    protocol: TCP
    port: 80
    targetPort: 51821
  type: LoadBalancer
