---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wireguard-pv
  namespace: wg
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/k3s/wireguard" 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-pvc
  namespace: wg
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
