---
- name: Deploy Atuin
  hosts: all

  pre_tasks:
    # Only works on Void Linux
    - name: Install packaging dependency
      xbps:
        name: python3-packaging
        state: present
      become: true

    - name: Install k8s required dependencies
      pip:
        name:
          - PyYAML
          - kubernetes
        extra_args: --break-system-packages
      become: true

  tasks:
    - name: Copy data folder to target hosts
      copy:
        src: ./manifests/
        dest: /tmp/atuin/manifests/
        mode: '0755'

    - name: Apply namespace
      k8s:
        state: present
        src: /tmp/atuin/manifests/namespace.yml

    - name: Apply secret
      k8s:
        state: present
        src: /tmp/atuin/manifests/secret.yml

    - name: Apply volume
      k8s:
        state: present
        src: /tmp/atuin/manifests/volume.yml

    - name: Apply service
      k8s:
        state: present
        src: /tmp/atuin/manifests/service.yml

    - name: Apply deployment
      k8s:
        state: present
        src: /tmp/atuin/manifests/deployment.yml

    - name: Apply cron job
      k8s:
        state: present
        src: /tmp/atuin/manifests/cron.yml

  post_tasks:
    - name: Cleanup data folder
      file:
        path: /tmp/atuin/manifests/
        state: absent
