---
- name: Test for raspberry pi /proc/cpuinfo
  command: grep -E "Raspberry Pi|BCM2708|BCM2709|BCM2835|BCM2836" /proc/cpuinfo
  register: grep_cpuinfo_raspberrypi
  failed_when: false
  changed_when: false

- name: Test for raspberry pi /proc/device-tree/model
  command: grep -E "Raspberry Pi" /proc/device-tree/model
  register: grep_device_tree_model_raspberrypi
  failed_when: false
  changed_when: false

- name: Set raspberry_pi fact to true
  set_fact:
    raspberry_pi: true
  when:
    grep_cpuinfo_raspberrypi.rc == 0 or grep_device_tree_model_raspberrypi.rc == 0

- name: Test for cmdline path
  stat:
    path: /boot/cmdline.txt
  register: boot_cmdline_path
  failed_when: false
  changed_when: false

- name: Set cmdline path on Raspberry Pi
  set_fact:
    cmdline_path: "/boot/cmdline.txt"
  when: boot_cmdline_path.stat.exists

- name: Activating cgroup support
  lineinfile:
    path: "{{ cmdline_path }}"
    regexp: '^(.*cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory.*)$'
    line: '\1'
    backrefs: true
    state: present
  notify: reboot
  when: raspberry_pi is defined and raspberry_pi
