---
- name: Reset Wireguard
  hosts: all

  tasks:
    - name: Copy data folder to target hosts
      copy:
        src: ./manifests/
        dest: /tmp/wireguard/manifests
        mode: '0755'

    - name: Delete deployment
      k8s:
        state: absent
        src: /tmp/wireguard/manifests/deployment.yml

    - name: Delete service
      k8s:
        state: absent
        src: /tmp/wireguard/manifests/service.yml

    - name: Delete volume
      k8s:
        state: absent
        src: /tmp/wireguard/manifests/volume.yml

    - name: Delete namespace
      k8s:
        state: absent
        src: /tmp/wireguard/manifests/namespace.yml

  post_tasks:
    - name: Cleanup the data folder
      file:
        path: /tmp/wireguard/
        state: absent
