---
- name: Deploy Wireguard
  hosts: all
  pre_tasks:
    # Only works on Void Linux
    - name: Install packaging dependency
      xbps:
        name: python3-packaging
        state: present
      become: true

    - name: Install k8s required dependencies
      pip:
        name:
          - PyYAML
          - kubernetes
        extra_args: --break-system-packages
      become: true

  tasks:
    - name: Copy data folder to target hosts
      copy:
        src: ./data/
        dest: /tmp/data/
        mode: '0755'

    - name: Apply namespace
      k8s:
        state: present
        src: /tmp/data/namespace.yml

    - name: Apply volume
      k8s:
        state: present
        src: /tmp/data/volume.yml

    - name: Apply service
      k8s:
        state: present
        src: /tmp/data/service.yml

    - name: Apply deployment
      k8s:
        state: present
        src: /tmp/data/deployment.yml

    - name: Cleanup data folder
      file:
        path: /tmp/data/
        state: absent
